/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package proyecto1.views;

import java.io.FileWriter;
import java.io.FileReader;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import proyecto1.controllers.ProductoControllers;
import proyecto1.models.ProductoModels;


/**
 *
 * @author Miguer Corado
 */
public class VistaReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaReportes.class.getName());

    /**
     * Creates new form VistaReportes
     */
    public VistaReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStock = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BERSHKA ");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("SELECCIONA TU OPCION");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BERSHKA ");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("SELECCIONA TU OPCION");

        btnStock.setBackground(new java.awt.Color(210, 230, 255));
        btnStock.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GENERAR REPORTE STOCK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Bahnschrift", 0, 12))); // NOI18N
        btnStock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnStock.addActionListener(this::btnStockActionPerformed);

        btnVentas.setBackground(new java.awt.Color(210, 230, 255));
        btnVentas.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GENERAR REPORTE DE VENTAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Bahnschrift", 0, 12))); // NOI18N
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVentas.addActionListener(this::btnVentasActionPerformed);

        jButton1.setBackground(new java.awt.Color(210, 230, 255));
        jButton1.setText("CERRAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel4)
                        .addGap(0, 293, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStock, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
       generarReporteStock();
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        generarReporteVentas();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaReportes().setVisible(true));
    }
    
    //HTML REPORTE VENTA
    private void generarReporteVentas() {

    try {

        BufferedReader reader = new BufferedReader(new FileReader("ventas.txt"));

        String fechaArchivo = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("dd_MM_yyyy_HH_mm_ss"));

        String nombreArchivo = fechaArchivo + "_Venta.html";

        FileWriter writer = new FileWriter(nombreArchivo);

        writer.write("<html>");
        writer.write("<head>");
        writer.write("<title>Reporte de Ventas</title>");

        writer.write("<style>");
        writer.write("body{font-family:Arial;background:#f4f4f4;text-align:center;}");
        writer.write("h1{color:#333;}");
        writer.write("table{margin:20px auto;border-collapse:collapse;width:80%;background:white;}");
        writer.write("th,td{border:1px solid #ccc;padding:10px;text-align:center;}");
        writer.write("th{background:#333;color:white;}");
        writer.write("tr:nth-child(even){background:#f2f2f2;}");
        writer.write("</style>");

        writer.write("</head>");
        writer.write("<body>");

        writer.write("<h1>Reporte de Ventas - BERSHKA</h1>");

        writer.write("<table>");

        writer.write("<tr>");
        writer.write("<th>ID</th>");
        writer.write("<th>Producto</th>");
        writer.write("<th>Cantidad</th>");
        writer.write("<th>Total</th>");
        writer.write("<th>Fecha</th>");
        writer.write("</tr>");

        String linea;

        while ((linea = reader.readLine()) != null) {

            String[] datos = linea.split("\\|");

            writer.write("<tr>");

            for (int i = 0; i < datos.length; i++) {
                writer.write("<td>" + datos[i] + "</td>");
            }

            writer.write("</tr>");
        }

        writer.write("</table>");
        writer.write("</body>");
        writer.write("</html>");

        reader.close();
        writer.close();

        JOptionPane.showMessageDialog(this, "Reporte generado correctamente");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar el reporte");
    }
}

    
    //HTML REPORTE STOCK
    private void generarReporteStock() {

    try {

        String fechaArchivo = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("dd_MM_yyyy_HH_mm_ss"));

        String nombreArchivo = fechaArchivo + "_Stock.html";

        FileWriter writer = new FileWriter(nombreArchivo);

        writer.write("<html>");
        writer.write("<head>");
        writer.write("<title>Reporte de Stock</title>");

        writer.write("<style>");
        writer.write("body{font-family:Arial;background:#f4f4f4;text-align:center;}");
        writer.write("h1{color:#333;}");
        writer.write("table{margin:20px auto;border-collapse:collapse;width:80%;background:white;}");
        writer.write("th,td{border:1px solid #ccc;padding:10px;text-align:center;}");
        writer.write("th{background:#333;color:white;}");
        writer.write("tr:nth-child(even){background:#f2f2f2;}");
        writer.write("</style>");

        writer.write("</head>");
        writer.write("<body>");

        writer.write("<h1>Reporte de Stock - BERSHKA</h1>");

        writer.write("<table>");

        writer.write("<tr>");
        writer.write("<th>ID</th>");
        writer.write("<th>Nombre</th>");
        writer.write("<th>Categoría</th>");
        writer.write("<th>Precio</th>");
        writer.write("<th>Stock</th>");
        writer.write("</tr>");

        for (int i = 0; i < ProductoControllers.contador; i++) {

            ProductoModels p = ProductoControllers.productos[i];

            writer.write("<tr>");

            writer.write("<td>" + p.id + "</td>");
            writer.write("<td>" + p.nombre + "</td>");
            writer.write("<td>" + p.categoria + "</td>");
            writer.write("<td>" + p.precio + "</td>");
            writer.write("<td>" + p.stock + "</td>");

            writer.write("</tr>");
        }

        writer.write("</table>");
        writer.write("</body>");
        writer.write("</html>");

        writer.close();

        JOptionPane.showMessageDialog(this, "Reporte de Stock generado correctamente");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, "Error al generar el reporte");

    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
